### ISSUE TITLE
Criação do Modelo dados[6]

### ISSUE THREAD

**Issue by thiagosoara** [josjunior/Agri_Tec#14]

**Comment by darllesDan** [comment]
Segue em Anexo o link do modelo de dados da AgriTec.

![Image](https://user-images.githubusercontent.com/101409253/169421961-031a8425-f727-4fed-92de-a56f2d716abc.png)



https://lucid.app/lucidchart/3b385d5a-27c4-4aea-bdbd-8d9a9724b331/edit?invitationId=inv_8a0ec7e5-9d4a-44ff-bcf5-dd60ca851b53
