### ISSUE TITLE
Reunir produtos agrícolas da região[6]

### ISSUE THREAD

**Issue by josjunior** [josjunior/Agri_Tec#20]

**Comment by darllesDan** [comment]
- Macaxeira
- cará
- Incana-de açúcar
- batata doce
- Mangas
- Uvas
- Fruta pão
- Laranja(tipos de laranja)
- Banana(tipos de banana)
- limão(tipos de limões)
- mamão(tipos de mamões)
- Araçá
- Azeitona (fruta pretinha)
- Pitomba
- Acerola
- Pinha
- Goiaba
- Maçã
- 
-
