### ISSUE TITLE
Coleta de dados do estoque de vendas [6]

### ISSUE THREAD

**Issue by josjunior** [josjunior/Agri_Tec#21]
- Pesquisar quais os alimentos mais populares na região
  - Pesquisar épocas onde  determinado alimento mais produção

**Comment by darllesDan** [comment]
**Frutas**

- Cará
- Batata doce
- Mangas
- Uvas
- Fruta pão
- Laranja(tipos de laranja)
- Banana(tipos de banana)
- Limão(tipos de limões)
- Mamão(tipos de mamões)
- Araçá
- Azeitona (fruta pretinha)
- Pitomba
- Acerola
- Pinha
- Goiaba
- Maçã
- Graviola
