### ISSUE TITLE
Criação do protótipo de alta fidelidade(informações nutricionais) [6]

### ISSUE THREAD

**Issue by josjunior** [josjunior/Agri_Tec#22]

**Comment by Itallakelly** [comment]
Segue em anexo o link para a visualização do protótipo. 
https://docs.google.com/document/d/1OZX-OQnQsXWtb6q2AfXHZrmY1qd9tOepgZqr55qaQF8/edit?usp=sharing

**Comment by josjunior** [comment]
protótipo especificamente das informações nutricionais dos alimentos 
https://docs.google.com/document/d/1IHIzKBElFvSFpOQS0OvRzGjczdVNCo8LN8lzCJaDb7M/edit?usp=sharing
