### ISSUE TITLE
Criar protótipo de baixa fidelidade [01]

### ISSUE THREAD

**Issue by darllesDan** [josjunior/Agri_Tec#38]

**Comment by JRodrigues23** [comment]
![Image](https://user-images.githubusercontent.com/102369219/171649054-a5b1ce9e-5d47-479f-8b6e-dddf256d6611.jpeg)
![Image](https://user-images.githubusercontent.com/102369219/171649055-a5230dbb-a993-4b5b-87bf-a73847cda25c.jpeg)
![Image](https://user-images.githubusercontent.com/102369219/171649056-048aeefa-e906-43b6-9e19-83a6e115fb72.jpeg)
![Image](https://user-images.githubusercontent.com/102369219/171649057-4825252e-41dc-48ec-93d8-d3b9726af2c2.jpeg)
