### ISSUE TITLE
Criar protótipo de alta fidelidade(Cadastrar Usuáriose [[)[02] 

### ISSUE THREAD

**Issue by thiagosoara** [josjunior/Agri_Tec#8]

**Comment by Itallakelly** [comment]
segue em anexo link para visualização do protótipo de alta fidelidade (cadastrar usuários e fornecedores)
https://docs.google.com/document/d/1xMmUqu43wst_ZlzVC6K3NKQ7IYbAKIU1TSw9aWvRDpM/edit?usp=sharing
